spring:
  profiles:
    active: mybatis
---
# mybatis 配置
spring:
  profiles: mybatis
# 对 mybatis 没用
#  jpa:
#    hibernate:
#      dialect:
#      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring-demo-guides?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
# mybatis 相关配置 **这里不需要配置也可以使用** `应该`是使用的 mybatis-spring-boot-starter 的原因不需要配置了
# mybatis:
  # mapper-locations: classpath*:com/example/mapper/*.xml
  # type-aliases-package: com.example.model
